spring:
  application:
    name: user
  profiles:
    active: dev
  config:
    import: optional:configserver:http://son:1234@localhost:9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://son:1234@localhost:8761/eureka
